version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - app-data:/var/www/html
    depends_on:
      - app
  app:
    build: ./docker/app
    environment:
      LOG_CHANNEL: stderr
      DB_CONNECTION: "pgsql"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "laravel"
      DB_USERNAME: "docker"
      DB_PASSWORD: "docker"
    ports:
      - "8000:8000"
    volumes:
      - app-data:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:12
    environment: 
      TZ: "Asia/Tokyo"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "laravel"
    volumes: 
      - db-data:/var/lib/mysql
volumes:
  app-data:
  db-data: